version: '3.4'
services:
  server:
    image: nginx
    ports:
      - 3000:3000
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./content:/usr/share/nginx/html
      - ./user_passwd:/usr/share/nginx/user_passwd
